### ISSUE TITLE
Password to edit passwd.yml

### ISSUE THREAD

**Issue by ahmad-alwazzan** [eanylin/ansible-lab#1]
Hello,

I will start by saying what an amazing work you have done.

What is the password for passwd.yml encrypted file? We need it to view and modify the content of it.

Thanks,

**Comment by eanylin** [comment]
Hi,

Thank you for your kind words.

The content in passwd.yml are mostly password variables, usernames etc. You can always create the file using ansible-vault.

More information on how to use ansible-vault can be found at https://docs.ansible.com/ansible/latest/user_guide/vault.html

Thanks.

Best Regards,
Anthony
