### ISSUE TITLE
oAUTH testing

### ISSUE THREAD

**Issue by Aniket-Utekar** [eanylin/ansible-lab#2]
Hi ,

You did a great job first of all!!

Just wanted to know how we can use make it more secure using oAUTH module.
I am able to trigger jobs using oAUTH module through servicenow.
But not able to understand how i can update servicenow ticket after completion of ansible-playbook.

Do you have any sample demo or code ready for it.
If yes please provide your feedback.

If no, you can mark this issue as closed.

Thanks

**Comment by eanylin** [comment]
Hi Aniket,

Unfortunately I have not tried/tested that yet. I will let you know if I work on it in future.

Thanks.

Best Regards,
Anthony
